import type { StellarNetworkName } from '@lumenlend/stellar';

export const STELLAR_NETWORK = (process.env.NEXT_PUBLIC_STELLAR_NETWORK as StellarNetworkName) || 'testnet';
export const STELLAR_RPC_URL = process.env.NEXT_PUBLIC_STELLAR_RPC_URL || 'https://soroban-testnet.stellar.org';
export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4000/api/v1';

export const CONTRACT_ADDRESSES = {
  lendingPool: process.env.NEXT_PUBLIC_LENDING_POOL_CONTRACT_ID || 'CDLENDINGPOOLPLACEHOLDER',
  collateralVault: process.env.NEXT_PUBLIC_COLLATERAL_VAULT_CONTRACT_ID || 'CDCOLLATERALVAULTPLACEHOLDER',
  liquidationEngine: process.env.NEXT_PUBLIC_LIQUIDATION_ENGINE_CONTRACT_ID || 'CDLIQUIDATIONENGINEPLACEHOLDER',
  oracleManager: process.env.NEXT_PUBLIC_ORACLE_MANAGER_CONTRACT_ID || 'CDORACLEMANAGERPLACEHOLDER',
  interestRateModel: process.env.NEXT_PUBLIC_INTEREST_RATE_MODEL_CONTRACT_ID || 'CDINTERESTRATEMODELPLACEHOLDER',
  usdc: process.env.NEXT_PUBLIC_USDC_CONTRACT_ID || 'CAQCFV44SC27F76B6J5SQ5F5Z2NV74G565TJX5NWLX2P7X76HGXUSDC7',
  xlm: process.env.NEXT_PUBLIC_XLM_CONTRACT_ID || 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCXLM',
};
